name: nurse_time
description: You Shift is am application to mantains shift in the hospital for the nurse
uses-material-design: true

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.pple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+16

flutter_launcher_name:
  name: "Shift You"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  firebase_core : ^1.2.1
  firebase_auth: ^3.1.3
  google_sign_in: ^5.0.4
  date_range_form_field: ^1.0.2
  get_it: ^7.1.3
  flutter_launcher_icons: ^0.9.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  logger: ^1.0.0
  intl: ^0.17.0
  fl_chart: ^0.40.2
  shared_preferences: ^2.0.7
  sign_in_with_apple: ^3.2.0
  flutter_signin_button: ^2.0.0
  crypto: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  bottom_navy_bar: ^6.0.0
  flutter_holo_date_picker: ^1.0.0-nullsafety.4
  flutter_translate: ^3.0.1
  flutter_translate_annotations: ^2.0.0
  in_app_review: ^2.0.3
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_translate_gen: ^2.0.0
  build_runner: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/web_hi_res_512.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: DsDigit
      fonts:
        - asset: assets/fonts/digital/DSDIGI.ttf
        - asset: assets/fonts/digital/DSDIGIB.ttf
        - asset: assets/fonts/digital/DSDIGII.ttf
        - asset: assets/fonts/digital/DSDIGIT.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/images/
      - assets/i18n/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
